  editor_selector : userEditor
  mode : specific_textareas
  theme : advanced
  #plugins : [spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template]
  theme_advanced_buttons1 : bold,italic,underline,blockquote,bullist,numlist,link,unlink,image
  theme_advanced_buttons2 : ""
  theme_advanced_buttons3 : ""
  theme_advanced_toolbar_location : top
  theme_advanced_toolbar_align : left
  skin : o2k7
  skin_variant : silver